### ISSUE TITLE
Create dummy data

### ISSUE THREAD

**Issue by samsaksfithian** [yamovie/client#1]
At least 5 movies
- [x] Title
- [x] Release year
- [x] Synopsis
- [x] Rating(s)
- [x] Runtime
- [x] Where to watch
- [x] Lead actors/actresses
- [x] Director
- [x] Genre
- [x] Media

**Comment by glenflorendo** [comment]
Movie data schema:

 title: String
 releaseYear: Number
 cast: String array
 director: String
 tags: Object
    genres: String array
    moods: String array
 ratings: Object
    mpaa: String
    rottenTomatoes: String
    imdb: Number
 plot: String
 media: Object
    posterUrl: String
    videoUrl: String
 quotes: String array
 runtime: Number (in minutes)
 streams: Object
