### ISSUE TITLE
More robust feedback form

### ISSUE THREAD

**Issue by samsaksfithian** [yamovie/client#170]
Need more questions and more granularity to get better information. 
https://docs.google.com/forms/d/1MYRMtG-FRNt1XNZ3ug0NFZ1wFigzSZiRSkIWdaaKgVI/edit?ts=5cb79fbe

See Aura feedback form: https://docs.google.com/forms/d/e/1FAIpQLSfgzzlxgcS1xzuNuIvByKPavX1orpAd3RC3fcmjdu7zimDJEg/viewform

**Comment by iylim** [comment]
updated feedback form. link is in discord

**Comment by samsaksfithian** [comment]
Updated! https://forms.gle/4BYLoWiotGzdkad58
