### ISSUE TITLE
Heroku/Express has memory leak warnings

### ISSUE THREAD

**Issue by samsaksfithian** [yamovie/client#195]
Heroku Logs:
`Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process.`

**Comment by glenflorendo** [comment]
**Solution 1:**
[Set a compatible session store](https://github.com/expressjs/session/blob/master/README.md#compatible-session-stores).
[Provide is as an option](https://github.com/expressjs/session/blob/master/README.md#store).
