### ISSUE TITLE
As a user I would like to see consistent design throughout the website

### ISSUE THREAD

**Issue by hanshank** [yamovie/client#65]
- [x] Use more of the red
- [x] Landing page tweak suggestions
  - [x] Fewer containers in the info
  - [x] Larger/consistent body text size
- [x] About page
  - [x] Dimmer background movie image
  - [x] Make mission text pop more
- [x] Nav bar
    - [x] Navbar bigger on some pages
- [x] Browse page

**Comment by samsaksfithian** [comment]
*Bug:* The navbar is taller/wider on the landing page than the other pages for some reason
